[package]
name = "sat"
version = "0.0.1"
authors = ["michaelbeaumont <mjboamail@gmail.com>"]

[lib]
name = "sat"
path = "src/lib.rs"

[[test]]
name = "tests"

[[bench]]
name = "benches"

[dependencies]
log="*"
env_logger="0.2.1"
glob="*"
